config/routes.rb
ArtzibitDev::Application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    mailers: "users/mailer"
  }

  get "page/home"

  resources :charges
  resources :test_users, only: [:create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # match "/auth/:provider/callback" => "sessions#create"
  # match "/signout" => "sessions#destroy", :as => :signout
  # match "/signin" => "sessions#new", :as => :signin
  resources :users, only: [:show]
  resources :artwork_styles, only: [:index]
  resources :orders, only: [:show]
  resources :artworks, only: [:index, :show, :new, :create, :edit, :update,
    :destroy] do
    collection do
      get "crop/:id", action: "crop", as: "crop"
      get "reprocess/:id", action: "reprocess", as: "reprocess"
    end
  end
  resources :artwork_approval_dtls, only: [:show]

  # ==================================================== #
  # =============  API Routes - Version 1  ============= #
  # ==================================================== #
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      devise_scope :user do
        scope "/users" do
          resources :registrations, only: [:create, :update, :destroy]
          resources :sessions, only: [:create, :destroy]
          resources :passwords, only: [:create]
        end
      end
      resources :users, only: [:show]
      resources :size_options, only: [:index]
      resources :categories, only: [:index]
      resources :artworks, only: [:index, :show, :new, :create, :edit, :update,
        :destroy]
      resources :artists, only: [:index]
      resources :user_favorites, only: [:index, :create, :update]
      resources :artwork_styles, only: [:index]
      resources :sizes, only: [:index]
      resources :event_batches, only: [:index, :show]
      resources :user_checked_ins, only: [:create]
      resources :carts, only: [:index, :show, :create, :update]
      resources :users, only: [:update]
      resources :orders, only: [:index, :show]
      resources :user_shipping_details, only: [:index, :create, :destroy, :update]
      resources :filters, only: [:index]
      resources :user_bank_details, only: [:index, :create]
      resources :artwork_markers, only: [:create]
      resources :user_views, only: [:create]
      resources :user_launch_app_counters, only: [:create]
      resources :user_app_tracking_logs, only: [:create]
      resources :user_activation_codes, only: [:create]
    end
  end
  root :to => "page#home"
end

app/controllers/api/v1/artworks_controller.rb
class Api::V1::ArtworksController < ApplicationController
  acts_as_token_authentication_handler_for User
  before_action :authenticate_user!
  respond_to :json
  def index
    @page_per_artwork = params[:page]
    if @page_per_artwork.blank?
      offset = 15 * 1.to_i
      limit = (15 - offset).abs
    else
      offset = 15 * params[:page].to_i
      limit = (15 - offset).abs
    end
    if params[:privacy].blank?
      @artworks = Artwork.all.actives.
      filter_by_artwork_style(params[:artwork_style_id]).
      filter_by_artist(params[:artist_id]).
      filter_by_privacy(params[:privacy]).
      reject{|a| (a.limited_edition == true and a.current_quantity <= 0)}.
      sort_by{|a| [(a.total_sales.to_i * -1), (a.total_favorites.to_i * -1), (a.created_at.to_i * -1)]}
    else
      @artworks = Artwork.all.actives.
      filter_by_artist(params[:artist_id]).
      filter_by_privacy(params[:privacy]).
      order(:id)
    end
    unless params[:all] == "true"
      @artworks = @artworks.uniq.first(offset).drop(limit)
    end

    render json: {status: true, data: @artworks.map{|a| a.v1_format("index",
      (current_user.blank? ? nil : current_user.id))} }
  end
  def show
    @artwork = Artwork.find_by_id params[:id]
    unless @artwork.blank?
      render json: {status: true, data: @artwork.v1_format("show",
        (current_user.blank? ? nil : current_user.id))}
    else
      render json: {status: false, message: "No Artwork found."}
    end
  end
  def new
    @styles = ArtworkStyle.all.map{|as| as.v1_format}
    render json: {status: true, data: @styles }
  end
  def edit
    @artwork = Artwork.find_by id: params[:id]
    unless @artwork.blank?
      if @artwork.user_id == current_user.id
        render json: {status: true, data: @artwork.v1_format}
      else
        render json: {status: false, message: "You have no right to update this artwork"}
      end
    else
      render json: {status: false, message: "No Artwork found."}
    end
  end
  def create
    @artwork = Artwork.new artwork_params
    @artwork.user_id = current_user.id
    if @artwork.save
      render json: {status: true, data: @artwork.v1_format("index",
      (current_user.blank? ? nil : current_user.id))}
    else
      render json: {status: false, message: @artwork.errors.full_messages.first}
    end
  end
  def update
    @artwork = Artwork.find_by id: params[:id]
    unless @artwork.blank?
      unless check_mark_up_params.blank?
        if @artwork.update_attributes(check_mark_up_params)
          render json: {status: true, data: @artwork.v1_format("show"), message: "Artwork updated successfully"}
        else
          render json: {status: false, message: @artwork.errors.full_messages.first}
        end
      else
        if @artwork.update_attributes(artwork_params)
          render json: {status: true, data: @artwork.v1_format("show"), message: "Artwork updated successfully"}
        else
          render json: {status: false, message: @artwork.errors.full_messages.first}
        end
      end
    else
      render json: {status: false, message: "No Artwork Found"}
    end
  end
  def destroy
    @artwork = Artwork.find_by id: params[:id]
    unless @artwork.blank?
      @artwork.destroy
      render json: {status: true, message: "Artwork successfully deleted"}
    else
      render json: {status: false, message: "No Artwork found."}
    end
  end
  def destroy
    @artwork = Artwork.find_by id: params[:id]
    unless @artwork.blank?
      if @artwork.can_be_deleted?
        begin
          @artwork.destroy
        rescue
          @artwork.active = false
          @artwork.save
        end
      else
        @artwork.active = false
        @artwork.save
      end
      render json: {status: true, message: "Artwork succesfully deleted"}
    else
      render json: {status: false, message: "Cannot find Artwork"}
    end
  end
  private
  def check_mark_up_params
    artwork = Artwork.find_by id: params[:id]
    new_params = artwork_params
    unless artwork.blank?
      mark_up_params =  artwork_params[:mark_up_prices_attributes]
      unless mark_up_params.blank?
        if mark_up_params.first[:percentage] == artwork.current_markup.try(:percentage)
          new_params = artwork_params.except(:mark_up_prices_attributes)
        end
      end
    end
    new_params
  end
  def artwork_params
    if action_name == "create"
      params_avatar = params[:artwork][:artwork_images_attributes].first[:image] = params[:artwork][:artwork_images_attributes].first[:image]
      params[:artwork][:artwork_images_attributes].first[:image] = params[:artwork][:artwork_images_attributes].first[:image] = format_image(params_avatar)
      params.required(:artwork).permit(:id, :name, :description, :artwork_style_id,
        :size_option_id, :limited_edition, :quantity, :privacy,
        artwork_images_attributes: [:id, :image], mark_up_prices_attributes: [:id,:percentage])
    else
      params.required(:artwork).permit(:id, :name, :description, :artwork_style_id,
        :size_option_id, :privacy, artwork_images_attributes: [:id, :image],
        mark_up_prices_attributes: [:id,:percentage])
    end
  end
  def format_image!
    params_avatar = artwork_params[:artwork_images_attributes].first[:image]
    unless params_avatar.blank?
      avatar = params_avatar
      artwork_params[:artwork_images_attributes].first[:image] = format_image avatar
    end
  end
  def format_image image_data
    data = nil
    unless image_data.blank?
      data = StringIO.new(Base64.decode64(image_data))
      data.class.class_eval {attr_accessor :original_filename, :content_type}
      data.original_filename = "User/Image" + Time.now.to_s.gsub(" ","_")
      data.content_type = "image/jpg"
    end
    return data
  end
  # def authenticate_user!
  #   unless current_user
  #     #do nothing
  #   end
  # end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :authenticate_user!
  layout "application"
  # before_action :validate_image, only: :create
  def index
    @all_artworks = current_user.artworks.actives
    if params[:scope] == "public"
      @artworks = current_user.artworks.public_artworks.actives
    elsif params[:scope] == "private"
      @artworks = current_user.artworks.private_artworks.actives
    else
      @artworks = @all_artworks.order("id desc")
    end
  end
  def show
    @artwork = Artwork.find_by id: params[:id]
  end
  def new
    @artwork = Artwork.new
    @bg_image = "microsite-bg-half-green.jpg"
    @color = "#777";
    @square_fixed_sizes = FixedSize.where(size_type: "square").order(:id)
    @landscape_fixed_sizes = FixedSize.where(size_type: "landscape").order(:id)
    @portrait_fixed_sizes = FixedSize.where(size_type: "portrait").order(:id)
  end
  def create
    @bg_image = "microsite-bg-half-green.jpg"
    @color = "#777";
    @artwork = Artwork.new artwork_params
    if @artwork.save
      flash[:notice] = "Successfully created user."
      redirect_to artworks_path
    else
      render :new
    end
  end
  def edit
    preview_crop_params
    case @art.orientation
      when "portrait"
        @portrait_fixed_sizes = FixedSize.where(size_type: "portrait").order(:id)
        @orientation = "portrait"
      when "landscape"
        @landscape_fixed_sizes = FixedSize.where(size_type: "landscape").order(:id)
        @orientation = "landscape"
      else
        @square_fixed_sizes = FixedSize.where(size_type: "square").order(:id)
        @orientation = "square"
    end
  end
  def reprocess
    @artwork = Artwork.find(params[:id])
    @artwork.artwork_images.each do |art_image|
      art_image.image.reprocess!
    end
    redirect_to artworks_path
  end
  def update
    @artwork = Artwork.find(params[:id])
    preview_crop_params
    if @artwork.update_attributes artwork_params
      unless artwork_image_params.blank?
        @artwork.update_attributes artwork_image_params
        @artwork.artwork_images.each do |art_image|
          art_image.image.reprocess!
        end
      end
      flash[:notice] = "Successfully updated user."
      redirect_to artworks_path
    else
      render :action => 'edit'
    end
  end
  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy
    redirect_to artworks_path
  end
  private
  def preview_crop_params
    @artwork = Artwork.find params[:id]
    @art = @artwork.artwork_images.first
    @art_image = @art.image
    width = @art_image.width
    height = @art_image.height
    case @art.orientation
      when "portrait"
        @set_select = [0, 0, 200, 300]
        @width_cood = 200
        @length_cood = 300
        @aspect_ratio = 0.67
        height_aspect_ratio = height.to_f/width.to_f
        @height_var = 400 * height_aspect_ratio
        @width_var = 400
      when "landscape"
        @set_select = [0, 0, 300, 200]
        @width_cood = 300
        @length_cood = 200
        @aspect_ratio = 1.5

        height_aspect_ratio = height.to_f/width.to_f
        @height_var = 400 * height_aspect_ratio
        @width_var = 400

      else
        @set_select = [0, 0, 100, 100]
        @width_var = 400
        @height_var = 400
        @width_cood = 100
        @length_cood = 100
        @aspect_ratio = 1
    end
  end
  def artwork_image_params
    params.required(:artwork).permit(:id, artwork_images_attributes: [:id, :crop_x, :crop_y, :crop_w, :crop_h])
  end
  def artwork_params
    if action_name == "create"
      params.required(:artwork).permit(:id, :name, :category_id, :artwork_style_id,
        :user_id, :description, :privacy, :limited_edition, :quantity, artwork_images_attributes: [:image],
        mark_up_prices_attributes: [:percentage])
    else
      params.required(:artwork).permit(:id, :name, :description, :category_id, :artwork_style_id, :cropping,
        artwork_images_attributes: [:id, :image, :crop_x, :crop_y, :crop_w, :crop_h],
        mark_up_prices_attributes: [:id, :percentage])
    end
  end
end

app/views/artworks/_artwork_show.html.erb
<div class="page-mask-dynamic" id="page-mask_<%= artwork.id %>" style="display:none;"
  onclick= "this.style.display='none';">
  <div class="artwork-detail">
    <div class="col-md-10 col-md-offset-1">
      <div class="row">
        <div class="artwork-dtl-heading" align="left">
            <h3><%= artwork.name %> (<%= artwork.featured_artwork_image.orientation %>) </h3>
        </div>
      </div>
      <div class="row">
        <div class="artwork-dtl-status">
          <div class="artwork-dtl-info col-md-6" align="left">
            <h5><b>STATUS:&nbsp;</b>
              <% unless artwork.right_aspect_ratio? %>
                Need to crop
              <% else %>
                Approved
              <% end %>
            </h5>
          </div>
          <div class="artwork-dtl-info col-md-6" align="right">
            <h5><i> Submitted: &nbsp; <%= artwork.created_at.strftime("%d-%b-%Y") %> </i></h5>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="artwork-dtl-image">
          <%= image_tag image_url(artwork.featured_artwork_image.image.url(:medium)),
          onclick: "document.getElementById('page-mask_#{artwork.id}').style.display='block';"
          %>
        </div>
      </div>
      <div class="row">
        <div class="artwork-dtl-desc" align="left">
          DESCRIPTION<h5><p class="artwork_desc"><%= artwork.description %></p></h5>
        </div>
      </div>
      <hr/>
      <div class="row">
        <span class="pull-left"><b>GENRE</b></span>
        <h5>
          <span class="cat_name pull-right"> <%= ArtworkStyle.find_by(id: artwork.artwork_style_id).try(:name) %> </span>
        </h5>
      </div>
      <hr/>
      <div class="row">
        <span class="pull-left"><b>PRICE</b></span>
        <h5>
        <span class="cat_name pull-right"> $ <%= artwork.featured_price %> </span>
        </h5>
      </div>
      <br/>
    </div>
  </div>
</div>

app/views/artworks/_mark_up_prices.html.erb
<% unless @square_fixed_sizes.blank? %>
  <div class="form-group" id="square_sizes" style="display:
    <%= @orientation.blank? ? 'none' : (@orientation == 'square') ? 'block' : 'none' %> ;">
    <div class="col-md-12">
      <table width="100%" border=0>
        <tr>
          <th width="60%">PRINT SIZE</tH>
          <th width="20%" style="text-align:center;">YOUR PROFIT</tH>
          <th width="20%" style="text-align:center;">RETAIL</tH>
        </tr>
        <% @square_fixed_sizes.each_with_index do |s,index| %>
        <tr>
          <td width="60%" style="padding:5px;"> <%= s.name_with_no %> </td>
          <td width="20%" style="padding:5px;" align="center">
            <input type="text" value="<%= s.current_price %>" id="square_base_<%= index %>" hidden>
            <input type="text" class="square_fields like-button form-control" value="<%= s.current_price %>" style="text-align:center;background-color:white;" disabled=true id="square_<%= index %>">
          </td>
          <td width="20%" style="padding:5px;" align="center">
            <input type="text" class="like-button form-control" value="<%= s.current_price %>" style="text-align:center;background-color:white;" id="square_retail_<%= index %>" disabled=true>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
<% end %>
<% unless @landscape_fixed_sizes.blank? %>
  <div class="form-group" id="landscape_sizes" style="display:
    <%= @orientation.blank? ? 'none' : (@orientation == 'landscape') ? 'block' : 'none' %> ;">
    <div class="col-md-12">
      <table width="100%" border=0>
        <tr>
          <th width="60%">PRINT SIZE</td>
          <th width="20%" align="center">YOUR PROFIT</td>
          <th width="20%" align="center">RETAIL</td>
        </tr>
        <% @landscape_fixed_sizes.each_with_index do |s, index| %>
        <tr>
          <td width="60%" style="padding:5px;"> <%= s.name_with_no %> </td>
          <td width="20%" style="padding:5px;" align="center">
            <input type="text" value="<%= s.current_price %>" id="landscape_base_<%= index %>" hidden>
            <input type="text" class="landscape_fields like-button form-control" value="<%= s.current_price %>" style="text-align:center;background-color:white;" disabled=true id="landscape_<%= index %>">
          </td>
          <td width="20%" style="padding:5px;" align="center">
            <input type="text" class="like-button form-control" value="<%= s.current_price %>" style="text-align:center;background-color:white;" id="landscape_retail_<%= index %>" disabled=true>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
<% end %>
<% unless @portrait_fixed_sizes.blank? %>
  <div class="form-group" id="portrait_sizes" style="display:
    <%= @orientation.blank? ? 'none' : (@orientation == 'portrait') ? 'block' : 'none' %> ;">
    <div class="col-md-12">
      <table width="100%" border=0>
        <tr>
          <th width="60%">PRINT SIZE</td>
          <th width="20%" align="center">YOUR PROFIT</td>
          <th width="20%" align="center">RETAIL</td>
        </tr>
        <% @portrait_fixed_sizes.each_with_index do |s, index| %>
        <tr>
          <td width="60%" style="padding:5px;"> <%= s.name_with_no %> </td>
          <td width="20%" style="padding:5px;" align="center">
            <input type="text" value="<%= s.current_price %>" id="portrait_base_<%= index %>" hidden>
            <input type="text" class="portrait_fields like-button form-control" value="<%= s.current_price %>" style="text-align:center;background-color:white;" disabled=true id="portrait_<%= index %>">
          </td>
          <td width="20%" style="padding:5px;" align="center">
            <input type="text" class="like-button form-control" value="<%= s.current_price %>" style="text-align:center;background-color:white;" id="portrait_retail_<%= index %>" disabled=true>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
<% end %>

app/views/artworks/edit_artwork.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="edit-artwork-label" align="center">
      <h4>
        EDIT ARTWORK
      </h4>
    </div>
  </div>
</div>
<%= form_for(@artwork) do |f| %>
<div class="row">
  <div class="col-md-3 col-md-offset-2">
    <div class="row">
      <%= f.fields_for :artwork_images, @artwork.artwork_images do |a| -%>
        <div class="edit-artwork-image">
          <!-- <div class="form-image"> -->
            <%= image_tag image_url(@artwork.featured_artwork_image.image.url(:medium)),
              class: "img-thumbnail"%>
              <br/>
              <br/>
            <div class="change-image">
              <label for="artwork_artwork_images_attributes_0_image"
                class="btn btn-primary btn-artist-type like-button artwork_upload">
                CHANGE IMAGE
              </label>
              <br/>
              <span class="image-filename"></span>
              <%= a.file_field :image, onchange: "$(this).parent().parent().find('.image-filename').html($(this).val().split(/[\\\\|/]/).pop());", style: "display: none;" %>
            </div>
          <!-- </div> -->
        </div>
      <% end -%>
    </div>
  </div>
  <div class="col-md-7 edit-artwork-detail">
    <div class="col-md-10">
      <% if @artwork.errors.any? %>
        <%= custom_error_messages @artwork %>
      <% end %>
      <div class="row">
        <div class="form-group">
          <%= f.text_field :name, class: "form-control like-button", placeholder: "Title" %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, class: "form-control like-button", placeholder: "Description", rows: 6 %>
        </div>
        <div class="form-group">
          <%= f.select(:category_id, Category.all.map{|u|[u.name, u.id]}, {}, {class: "form-control like-button", prompt: "Category"}) %>
        </div>
        <div class="form-group">
          <%= f.select(:artwork_style_id, ArtworkStyle.all.map{|u|[u.name, u.id]}, {}, {class: "form-control", prompt: "Style"}) %>
        </div>
      </div>
      <div class="row">
        <br/><br/><br/><br/>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group">
    <div class="text-center">
      <%= f.hidden_field :id, value: "#{f.object.id}" %>
      <%= f.submit "SUBMIT ARTWORK", class: "btn btn-primary btn-lg like-button btn-artist-type" %>
    </div>
  </div>
</div>
<% end %>

app/views/artworks/index.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="page-label" align="center">
      <h3>
        WELCOME, <%= current_user.name.upcase %>
      </h3>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-4 col-xs-offset-4">
    <div class="index-menu-div text-center" align="center">
        <ul class="nav nav-pills index-menu scopes table_tools_segmented_control">
          <li role="presentation" class="<%= params[:scope].blank? ? 'active' : '' %>  index-menu-li">
            <%= link_to "All", artworks_path, class: "index-menu-all" %>
          </li>
          <li role="presentation" class="<%= params[:scope] == 'public' ? 'active' : '' %>  index-menu-li">
            <%= link_to "Public", artworks_path(scope: "public"), class: "index-menu-public" %>
          <li role="presentation" class="<%= params[:scope] == 'private' ? 'active' : '' %>  index-menu-li">
            <%= link_to "Private", artworks_path(scope: "private"), class: "index-menu-private" %>
          </li>
        </ul>
    </div>
  </div>
</div>
<% unless @all_artworks.blank? %>
  <div class="row">
    <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10
      col-xs-offset-1">
      <div class="row">
        <% @artworks.each_with_index do |artwork, index| %>
          <div class="col-lg-3 col-md-3 col-sm-4 col-xs-12 artwork-list">
            <div class= "artwork-box">
              <% if artwork.featured_artwork_image.image.processing? %>
                <div class="artwork-dtl-image-square">
              <% else %>
                <div class="artwork-dtl-image-<%= artwork.featured_artwork_image.orientation %>">
              <% end %>
              <% if artwork.featured_artwork_image.blank?%>
                <% artwork_image = "artzibit-logo.png" %>
              <% else %>
                <% artwork_image = artwork.featured_artwork_image.image.url(:medium) %>
              <% end %>
              <%= image_tag image_url(artwork_image), onclick: "document.getElementById('page-mask_#{artwork.id}').style.display='block';",
                class: "img-thumbnail #{'to-crop' unless artwork.right_aspect_ratio?}"%>
              <br/>
              </div>
            </div>
            <div class="artwork-title truncate">
              <p><h5> <%= artwork.name %> (<%= artwork.featured_artwork_image.orientation %>) </h5></p>
            </div>
            <div class="artwork-status">
              <% unless artwork.right_aspect_ratio? %>
                <h5> Need to crop </h5>
              <% else %>
                <h5> Approved </h5>
              <% end %>
            </div>
            <div class="artwork-actions">
              <hr class="margin-less">
              <div class="row">
                <div class="col-md-8">
                  <p><i>Submitted</i>: <%= artwork.created_at.strftime("%d-%b-%Y") %></p>
                </div>
                <div class="col-md-4 gray" style="text-align:right;">
                  <%= link_to edit_artwork_path(artwork), onclick: (artwork.
                      featured_artwork_image.image.processing? ?
                      "alert('Your image is still processing. Please try again later.'); return false" : "return true") do %>
                    <span class="glyphicon glyphicon-edit"> </span >
                  <% end %>
                  <%= link_to artwork_path(artwork), method: :delete,
                    data: {:confirm => "Are you sure you want to delete"} do %>
                    <span class="glyphicon glyphicon-trash"> </span >
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% @artworks.each do |artwork| %>
    <%= render "artwork_show", artwork: artwork %>
  <% end %>
<% else %>
  <div class="row" align="center">
    <div class="col-md-4 col-md-offset-4">
      <p>Seems like you haven't uploaded anything yet...</p>
    </div>
  </div>
  <div class="row" align="center">
    <div class="col-md-2 col-md-offset-5">
      <%= link_to "START SELLING ART", new_artwork_path, style: "color:#{@color};
      text-decoration:none;", class: "btn btn-default form-control
      like-button blue-green" %>
    </div>
  </div>
<% end %>

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

<script type="text/javascript">
  function ConfirmDelete() {
    alert(confirm('Are you sure you want to delete this Artwork?'));
  }
</script>

app/views/artworks/show.html.erb
<div class="order_form" width="100%">
  <center>
    <table width="65%" border="0">
    <tr><td align="center">
      <br/><br/>
    </td></tr>
    <tr><td align="center">
    <p> <h2 style="color:#2bcba5;"> THANK YOU FOR YOUR SUBMISSION</h2> </p>
    </td></tr>
    <tr><td align="center">
    <p>Your artwork is now on approval process from Artzibit curators. This usually takes 2 - 3 days.</p>
    </td></tr>
    <tr><td align="center">
      <%#= image_tag attachments["image.png"].url, width: "100%", height: "100%" %>
    </td></tr>
    <tr><td align="center">
      <br/>
      <br/>
    </td></tr>
    </table>
    <table width="65%" border="0">
    <tr>
      <td width="50%">
        Artwork Name<br>
        <h4> <%= @artwork.name %></h4>
      </td>
      <td width="50%" align="right">
        Artwork No.<br>
        <h4> <%= @artwork.id %> </h4>
      </td>
    </tr>
    <tr>
      <td width="50%">
        Artist Name <br>
        <h4> <%= @artwork.user.name %></h4>
      </td>
      <td width="50%" align="right">
        Date Submitted<br>
        <h4> <%= @artwork.created_at.strftime('%A, %b %d, %Y') %> </h4>
      </td>
    </tr>
    <tr>
      <td colspan=2>
        Description <br>
        <p><h4> <%= @artwork.description %></h4></p>
      </td>
    </tr>
    <tr>
      <td colspan=2 align="center">
        <br/>
      </td>
    </tr>
    </table>
    <hr>
    <table width="65%" border="0">
    <tr><td align="center" colspan="3">
    <p> <h3 style="color:#2bcba5;"> PROJECTED EARNINGS </h3> </p>
    </td></tr>
    <tr>
      <th style="text-align:center" width="33%">
        SIZES
      </th>
      <th style="text-align:center" width="33%">
        YOUR PROFIT
      </th>
      <th style="text-align:center" width="33%">
        RETAIL
      </th>
    </tr>
    <% @artwork.fixed_artwork_sizes.order(:width).each do |size| %>
        <tr>
        <th style="text-align:center" width="33%">
          <h6><%= size.name_with_no %></h6>
        </th>
        <th style="text-align:center" width="33%">
          $ <%= @artwork.markup_price(size.current_price) %>
        </th>
        <th style="text-align:center" width="33%">
          $ <%= size.current_price + @artwork.markup_price(size.current_price) %>
        </th>
      </tr>
    <% end %>
    </table>


    <table width="80%" border="0">
      <tr>
        <td width="50%">
          <!-- <p> <h5> <%#= image_tag attachments["ig.png"].url, width: "7%", height: "7%"%> instagram </h5> </p> -->
          xxx
        </td>
        <td width="50%" align="right">
          <p> <h5> (+65)4531 5638 </h5>
          <h5> contact@artzibit.net</h5> </p>
        </td>
      </tr>
    </table>
  </center>
</div>