config/routes.rb
ArtzibitDev::Application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    mailers: "users/mailer"
  }

  get "page/home"

  resources :charges
  resources :test_users, only: [:create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # match "/auth/:provider/callback" => "sessions#create"
  # match "/signout" => "sessions#destroy", :as => :signout
  # match "/signin" => "sessions#new", :as => :signin
  resources :users, only: [:show]
  resources :artwork_styles, only: [:index]
  resources :orders, only: [:show]
  resources :artworks, only: [:index, :show, :new, :create, :edit, :update,
    :destroy] do
    collection do
      get "crop/:id", action: "crop", as: "crop"
      get "reprocess/:id", action: "reprocess", as: "reprocess"
    end
  end
  resources :artwork_approval_dtls, only: [:show]

  # ==================================================== #
  # =============  API Routes - Version 1  ============= #
  # ==================================================== #
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      devise_scope :user do
        scope "/users" do
          resources :registrations, only: [:create, :update, :destroy]
          resources :sessions, only: [:create, :destroy]
          resources :passwords, only: [:create]
        end
      end
      resources :users, only: [:show]
      resources :size_options, only: [:index]
      resources :categories, only: [:index]
      resources :artworks, only: [:index, :show, :new, :create, :edit, :update,
        :destroy]
      resources :artists, only: [:index]
      resources :user_favorites, only: [:index, :create, :update]
      resources :artwork_styles, only: [:index]
      resources :sizes, only: [:index]
      resources :event_batches, only: [:index, :show]
      resources :user_checked_ins, only: [:create]
      resources :carts, only: [:index, :show, :create, :update]
      resources :users, only: [:update]
      resources :orders, only: [:index, :show]
      resources :user_shipping_details, only: [:index, :create, :destroy, :update]
      resources :filters, only: [:index]
      resources :user_bank_details, only: [:index, :create]
      resources :artwork_markers, only: [:create]
      resources :user_views, only: [:create]
      resources :user_launch_app_counters, only: [:create]
      resources :user_app_tracking_logs, only: [:create]
      resources :user_activation_codes, only: [:create]
    end
  end
  root :to => "page#home"
end

app/views/shared/_file_requirements.html.erb
<div class="col-md-8 col-md-offset-1">
  <div class="col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2 col-xs-10
    col-xs-offset-2">
    <div class="requirements">
      <div class="row">
        <div class="requirement-header">
          <h4> FILE REQUIREMENTS: </h4>
        </div>
        <div class="requirement-body">
          <ul>
            <li> High Res JPEG files </li>
            <li> RGB color mode</li>
            <li> At least 2500px at the smallest side </li>
            <li> Image resolution at 300dpi </li>
            <li> File size should not exceed 75mb</li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="requirement-header">
          <h4> THINGS TO REMEMBER: </h4>
        </div>
        <div class="requirement-body">
          <ul>
            <li> Each artwork will undergo an approval process from the Artzibit curators. This usually takes 2 – 3 days. </li>
            <li> Only one image upload is allowed for each artwork. If your image is still in pending status, you can still change images but this will reset the approval process.</li>
            <li> Artwork ratio should be 1:1 for square images or 3:2 for rectangle images.</li>
            <li> Try to keep important details away from the borders of the image. </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <% unless key == "notice" %>
    <div id="page-mask" %>
    <%= content_tag :div, value, id: "popup_#{key}", class: "col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-4 col-xs-offset-4" do %>
      <span class="close close-flash"> <%= image_tag "close.png", onclick: "closeButton();" %></span>
      <span> <%= flash["#{key}"]%> </span>
    <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_flash_not_popup.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, id: "#{key}" do %>
    <span> <%= flash["#{key}"]%> </span>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="col-xs-12 plr-185">
	<div class="container-fluid">
		<div class="row footer">
			<div class="col-md-4 ta-center-on-sm m-b-10">
				&copy; 2017 Artzibit
			</div>
			<div class="col-md-8 text-right ta-center-on-sm m-b-10">
				<a href="#" class="menu-item">About Artzibit</a>
				<a href="#" class="menu-item">Terms of Service</a>
				<a href="#" class="menu-item">FAQs</a>
				<a href="#" class="menu-item">Contact</a>
			</div>
		</div>
	</div>
</div>

app/views/shared/_navbar.html.erb
<!-- START HEADER AREA -->
<header class="header-area header-wrapper">
    <!-- header-middle-area -->
    <div id="sticky-header" class="header-middle-area plr-185">
        <div class="container-fluid">
            <div class="full-width-mega-dropdown">
                <div class="row">
                    <!-- logo -->
                    <div class="col-md-2 col-sm-6 col-xs-12">
                        <div class="logo">
                            <%= link_to root_path do %>
                                <%= image_tag "black_logo.png", alt: "Artzibit", class: "img-responsive" %>
                            <% end %>
                        </div>
                    </div>
                    <!-- primary-menu -->
                    <div class="col-md-10 hidden-sm hidden-xs">
                        <nav id="primary-menu">
                            <ul class="main-menu text-right">
                                <li><a href="#">Browse Artwork</a></li>
                                <% if current_user.blank? %>
                                <li>
                                  <%= link_to "Sign Up", new_registration_path(:user), class: "#{navbar_white_link_active(controller_name, action_name,
                                  'sign_up')}" %>
                                </li>
                                <li>
                                  <%= link_to "Sign In", new_session_path(:user), class: "#{navbar_white_link_active(controller_name, action_name, 'sign_in')}" %>
                                </li>
                                <% else %>

                                <li class="dropdown">
                                  <a href="#" class="dropdown-toggle <%= navbar_white_link_active(controller_name,
                                    action_name, 'profile') %>"
                                    data-toggle="dropdown"
                                    role="button" aria-haspopup="true" aria-expanded="false"
                                    style= "color:<%=@color%>;background-color:white;">
                                    PROFILE
                                      <span class="caret" style= "color:<%=@color%>;"></span>
                                  </a>
                                  <ul class="dropdown-menu">
                                    <li>
                                      <%= link_to artworks_path, style: "color:#{@color};" do %>
                                        MY ARTWORKS
                                      <% end %>
                                    </li>
                                    <li>
                                      <%= link_to edit_user_registration_path, style: "color:#{@color};" do %>
                                        EDIT PROFILE
                                      <% end %>
                                    </li>
                                    <li>
                                      <%= link_to destroy_user_session_path, method: "delete", style: "color:#{@color};" do %>
                                        SIGN OUT
                                      <% end %>
                                    </li>
                                  </ul>
                                </li>
                                <% end %>
                                
                                <li>
                                    <a href="#">
                                        <i class="zmdi zmdi-star-outline zmdi-hc-lg"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="zmdi zmdi-shopping-cart zmdi-hc-lg"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="zmdi zmdi-search zmdi-hc-lg"></i>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- END HEADER AREA -->

<!-- START MOBILE MENU AREA -->
<div class="mobile-menu-area hidden-lg hidden-md">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="mobile-menu">
                    <nav id="dropdown">
                       <ul>
                         <li><a href="#">Browse Artwork</a></li>
                                <li><a href="#">Sign up</a></li>
                                <li><a href="#">Sign in</a></li>
                                <li>
                                    <a href="#">
                                        <i class="zmdi zmdi-star-outline zmdi-hc-lg"></i>
                                        Favourites
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="zmdi zmdi-shopping-cart zmdi-hc-lg"></i>
                                        Cart
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="zmdi zmdi-search zmdi-hc-lg"></i>
                                        Search
                                    </a>
                                </li>
                       </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END MOBILE MENU AREA -->


<script type="text/javascript">
  function display_sign_in() {
    sign_in = document.getElementById("page-mask-signin");
    sign_form = document.getElementById("new_user_form");
    sign_in.style.display = "block";
    sign_form.style.display = "block";
  }
</script>

app/views/shared/_navbar_white.html.erb
<nav class="navbar navbar-white navbar-toggleable-md bg-inverse navbar-static-top navbar-default">  
    <div class="container">       
        <h1 class="logo">
            <%= link_to root_path, class: "navbar-brand" do %>
               <%= image_tag "black_logo.png", height: "130%" %>
            <% end %>
        </h1><!--//logo-->
        <nav class="main-nav navbar-right" role="navigation">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button><!--//nav-toggle-->
            </div><!--//navbar-header-->
            <div id="navbar-collapse" class="navbar-collapse collapse">
               <ul class="nav navbar-nav navbar-right">
              <% if current_user.blank? %>
                <li>
                  <%= link_to "Sign Up", new_registration_path(:user), style: "color:#{@color};",
                  class: "#{navbar_white_link_active(controller_name, action_name,
                  'sign_up')}" %>
                </li>
                <li>
                  <%= link_to "Sign In", new_session_path(:user), style: "color:#{@color};",
                    class: "#{navbar_white_link_active(controller_name, action_name, 'sign_in')}" %>
                </li>
              <% else %>
               <li class="dropdown">
                  <a href="#" class="dropdown-toggle <%= navbar_white_link_active(controller_name,
                    action_name, 'profile') %>"
                    data-toggle="dropdown"
                    role="button" aria-haspopup="true" aria-expanded="false"
                    style= "color:<%=@color%>;background-color:white;">
                    PROFILE
                      <span class="caret" style= "color:<%=@color%>;"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to artworks_path, style: "color:#{@color};" do %>
                        MY ARTWORKS
                      <% end %>
                    </li>
                    <li>
                      <%= link_to edit_user_registration_path, style: "color:#{@color};" do %>
                        EDIT PROFILE
                      <% end %>
                    </li>
                    <li>
                      <%= link_to destroy_user_session_path, method: "delete", style: "color:#{@color};" do %>
                        SIGN OUT
                      <% end %>
                    </li>
                  </ul>
                </li>
              <% end %>
          </ul>
            </div><!--//navabr-collapse-->
        </nav><!--//main-nav-->                     
    </div><!--//container-->
</nav><!--//header-->