config/routes.rb
ArtzibitDev::Application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    mailers: "users/mailer"
  }

  get "page/home"

  resources :charges
  resources :test_users, only: [:create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # match "/auth/:provider/callback" => "sessions#create"
  # match "/signout" => "sessions#destroy", :as => :signout
  # match "/signin" => "sessions#new", :as => :signin
  resources :users, only: [:show]
  resources :artwork_styles, only: [:index]
  resources :orders, only: [:show]
  resources :artworks, only: [:index, :show, :new, :create, :edit, :update,
    :destroy] do
    collection do
      get "crop/:id", action: "crop", as: "crop"
      get "reprocess/:id", action: "reprocess", as: "reprocess"
    end
  end
  resources :artwork_approval_dtls, only: [:show]

  # ==================================================== #
  # =============  API Routes - Version 1  ============= #
  # ==================================================== #
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      devise_scope :user do
        scope "/users" do
          resources :registrations, only: [:create, :update, :destroy]
          resources :sessions, only: [:create, :destroy]
          resources :passwords, only: [:create]
        end
      end
      resources :users, only: [:show]
      resources :size_options, only: [:index]
      resources :categories, only: [:index]
      resources :artworks, only: [:index, :show, :new, :create, :edit, :update,
        :destroy]
      resources :artists, only: [:index]
      resources :user_favorites, only: [:index, :create, :update]
      resources :artwork_styles, only: [:index]
      resources :sizes, only: [:index]
      resources :event_batches, only: [:index, :show]
      resources :user_checked_ins, only: [:create]
      resources :carts, only: [:index, :show, :create, :update]
      resources :users, only: [:update]
      resources :orders, only: [:index, :show]
      resources :user_shipping_details, only: [:index, :create, :destroy, :update]
      resources :filters, only: [:index]
      resources :user_bank_details, only: [:index, :create]
      resources :artwork_markers, only: [:create]
      resources :user_views, only: [:create]
      resources :user_launch_app_counters, only: [:create]
      resources :user_app_tracking_logs, only: [:create]
      resources :user_activation_codes, only: [:create]
    end
  end
  root :to => "page#home"
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :cart
  has_many :cart_items, through: :cart, dependent: :destroy
  has_many :order_histories, dependent: :destroy
  has_many :order_couriers, dependent: :destroy
  has_many :order_assignments, dependent: :destroy
  belongs_to :user_shipping_detail

  scope :order_submitted, -> {where(current_status: "order") }
  scope :printing, -> { where(current_status: "printing") }

  scope :ready_to_deliver, -> { where(current_status: "ready_to_deliver") }
  scope :on_delivery, -> { where(current_status: "on_delivery") }
  scope :completed, -> { where(current_status: "completed") }

  scope :assigned_ready_to_deliver, -> { where(current_status: "ready_to_deliver") }
  scope :assigned_on_delivery, -> { where(current_status: "on_delivery") }
  scope :assigned_completed, -> { where(current_status: "completed") }

  after_create :send_receipt
  after_save :update_artwork_fields

  def update_artwork_fields
    order = Order.find_by id: self.id
    order.cart_items.each do |ci|
      artwork = Artwork.find_by id: ci.artwork_id
      unless artwork.blank?
        artwork.total_sales = artwork.sales
        artwork.total_pieces_sold = artwork.pieces_sold
        artwork.save(validate: false)
      end
    end
  end

  def send_receipt
    OrderMailer.send_receipt(self).deliver_now
    # OrderMailer.notify_printer(self, AdminUser.default_printer_email.email).deliver_now unless AdminUser.default_printer_email.blank?
    OrderMailer.notify_printer(self, "gravides.dren@gmail.com").deliver_now
    OrderMailer.notify_assignment(self, "gravides.dren@gmail.com").deliver_now
  end

  def name
    "Order ##{id}"
  end
  def file_name
    "Order#{id}_#{user.username}"
  end
  def courier
    order_couriers.order("created_at desc").first
  end

  def assignee
    order_assignments.order("created_at desc").first.try(:admin_user)
  end

  def installation?
    cart.cart_items.select{|a| a.installation}.count > 0
  end

  def v1_format mode=""
    if mode == ""
    {
      id: id,
      status: OrderHistory::STATUS[current_status],
      no_of_items_in_order: cart.items_count,
      updated_date: updated_at.strftime("%Y-%m-%d"),
      updated_time: updated_at.strftime("%I:%M%p")
    }
    else
    {
      courier: courier_name,
      tracking_no: id,
      logistics_tracking: order_histories.order("created_at").map{|oh| oh.v1_format}
    }
    end
  end

  def courier_name
    if (current_status == "on_delivery" or current_status == "completed")
      if order_assignments.blank?
        AdminUser.printer_name
      else
        assignee.try(:name)
      end
    end
  end

  def card_stripe
    begin
      customer = Stripe::Customer.retrieve(user.stripe_id)
    rescue Stripe::InvalidRequestError
      nil
    else
      unless card_stripe_id.blank?
        begin
          card_detail = customer.sources.retrieve(card_stripe_id)
        rescue Stripe::InvalidRequestError
          nil
        else
          card_detail
        end
      end
    end
  end
  def card_description
    card_detail = card_stripe
    unless card_detail.blank?
    "BRAND: #{card_detail.brand} CARD NO: *****#{card_detail.last4} EXP: #{card_detail.exp_month}/#{card_detail.exp_year}"
    end
  end
  def last_process
    order_histories.order("processed_at desc").first
  end
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < UserModuleController
  def index
    @orders = current_user.orders
    render json: {status: true, data: @orders.map{|o| o.v1_format}}
  end
  def show
    @order = Order.find_by id: params[:id]
    unless @order.blank?
      render json: {status: true, data: @order.v1_format("show")}
    else
      render json: {status: false, message: "No order found"}
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find params[:id]
    @from = ["From", "1 Fusionopolis Pt, 301-28/29 Gelexis", "Singapore 138522",
      "+6574246884"]
    @to = ["To", "7 Jalan Kilang 02-01", "Singapore 138522",
      "+6574246884"]
  end
end

app/views/orders/show.html.erb
<% @artwork = ArtworkApprovalHdr.last.artwork %>

<div class="order_form" width="100%">
  <center>
  <table width="65%" border="0">
    <tr><td align="center">
      <br/><br/>
    </td></tr>
    <tr><td align="center">
    <p> <h2 style="color:#2bcba5;"> WE NEED YOUR ANSWER!</h2> </p>
    </td></tr>
    <tr><td align="center">
    <p>Please choose Approve or Reject for the Artwork below:</p>
    </td></tr>
    <tr><td align="center">
      <%= image_tag @artwork.featured_artwork_image.image.url(:medium) %>
    </td></tr>
    <tr><td align="center">
      <br/>
      <br/>
    </td></tr>
    </table>
    <table width="65%" border="0">
    <tr>
      <td width="50%">
        Artwork Name.<br>
        <h4> <%= @artwork.name %></h4>
      </td>
      <td width="50%" align="right">
        Artwork No.<br>
        <h4> <%= @artwork.id %> </h4>
      </td>
    </tr>
    <tr>
      <td colspan=2>
        Artist Name <br>
        <h4> <%= @artwork.user.name %></h4>
      </td>
    </tr>
    <tr>
      <td colspan=2>
        Description <br>
        <p><h4> <%= @artwork.description %></h4></p>
      </td>
    </tr>
    <tr><td align="center">
      <br/><br/>
    </td></tr>
    <tr>
      <td colspan=2 align="center">
        <%= link_to "APPROVE", admin_orders_url(scope: "assigned_ready_to_deliver"), class: "btn btn-lg btn-default",
          style: "width:150px;display:inline-block;margin-bottom:0;font-weight:normal;
          text-align:center;vertical-align:middle;cursor:pointer;
          background-image: none;border: 1px solid transparent;white-space:nowrap;
          user-select:none;background-color:#2bcba5;color:white;
          padding:10px 16px;font-size:18px;line-height:1.33;border-radius:6px;
          text-decoration:none;" %>
        <%= link_to "REJECT", admin_orders_url(scope: "assigned_ready_to_deliver"), class: "btn btn-lg btn-default",
          style: "width:150px;display:inline-block;margin-bottom:0;font-weight:normal;
          text-align:center;vertical-align:middle;cursor:pointer;
          background-image: none;border: 1px solid transparent;white-space:nowrap;
          user-select:none;background-color:red;color:white;
          padding:10px 16px;font-size:18px;line-height:1.33;border-radius:6px;
          text-decoration:none;" %>
      </td>
    </tr>
    <tr>
      <td colspan=2 align="center">
        <br/>
        <br/>
        <br/>
      </td>
    </tr>
    </table>
    <table width="80%" border="0">
      <tr>
        <td width="50%">
          <p> <h5> <%= image_tag image_path("ig.png"), width: "7%", height: "7%"%> instagram </h5> </p>
        </td>
        <td width="50%" align="right">
          <p> <h5> (+65)4531 5638 </h5>
          <h5> contact@artzibit.net</h5> </p>
        </td>
      </tr>
    </table>
  </center>
</div>